services:
  # Production service
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3456:3456"
    environment:
      - NODE_ENV=production
      - PORT=3456
      - API_PREFIX=/api
      - DOCS_ENABLED=true
      - CORS_ORIGIN=*
      - LOG_LEVEL=info
      - PRETTY_LOGGING=false
      - RATE_LIMIT_WINDOW=15
      - RATE_LIMIT_MAX=100
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3456/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  # Development service with hot reload
  api-dev:
    build:
      context: .
      target: builder
    command: npm run dev
    ports:
      - "3456:3456"
    environment:
      - NODE_ENV=development
      - PORT=3456
      - API_PREFIX=/api
      - DOCS_ENABLED=true
      - CORS_ORIGIN=*
      - LOG_LEVEL=debug
      - PRETTY_LOGGING=true
      - RATE_LIMIT_WINDOW=60
      - RATE_LIMIT_MAX=1000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
    profiles:
      - dev
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3456/api/v1/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s 